/**
 * Custom Agent Types - Types for user-defined AI agents (separate from Agent Runner)
 *
 * Custom agents are reusable agent configurations that can be created and managed
 * independently from the Agent Runner. They support custom prompts, tool selection,
 * MCP server integration, and model configuration.
 */

import type { McpServerConfig, ReasoningEffort } from './provider.js';
import type { ThinkingLevel } from './settings.js';
import type { ModelId } from './model.js';

/**
 * CustomAgentStatus - Lifecycle status of a custom agent
 */
export type CustomAgentStatus = 'draft' | 'active' | 'archived';

/**
 * CustomAgentTool - Tool configuration for a custom agent
 *
 * Defines which tools are available to the agent and any tool-specific settings.
 */
export interface CustomAgentTool {
  /** Tool identifier (e.g., 'bash', 'read', 'write', 'edit') */
  name: string;
  /** Whether this tool is enabled for the agent */
  enabled: boolean;
  /** Optional tool-specific configuration */
  config?: Record<string, unknown>;
}

/**
 * CustomAgentMCPServer - MCP server configuration for a custom agent
 *
 * References an MCP server from global settings with per-agent enablement.
 */
export interface CustomAgentMCPServer {
  /** MCP server ID (references MCPServerConfig.id from global settings) */
  serverId: string;
  /** Whether this server is enabled for the agent */
  enabled: boolean;
  /** Optional list of specific tools to enable from this server (empty = all tools) */
  enabledTools?: string[];
}

/**
 * CustomAgentModelConfig - Model configuration for a custom agent
 */
export interface CustomAgentModelConfig {
  /** Model to use for this agent */
  model: ModelId;
  /** Extended thinking level (only applies to Claude models) */
  thinkingLevel?: ThinkingLevel;
  /** Reasoning effort level (only applies to Codex models) */
  reasoningEffort?: ReasoningEffort;
  /** Maximum tokens for response */
  maxTokens?: number;
  /** Temperature for response generation (0-1) */
  temperature?: number;
}

/**
 * CustomAgent - A user-defined AI agent configuration
 *
 * Custom agents are stored in team storage and can be used across projects.
 * They define the agent's behavior, available tools, and model configuration.
 */
export interface CustomAgent {
  /** Unique identifier */
  id: string;
  /** Display name */
  name: string;
  /** Description of what this agent does */
  description: string;
  /** System prompt that defines the agent's behavior */
  systemPrompt: string;
  /** Current status of the agent */
  status: CustomAgentStatus;
  /** Model configuration */
  modelConfig: CustomAgentModelConfig;
  /** Available tools for this agent */
  tools: CustomAgentTool[];
  /** MCP servers available to this agent */
  mcpServers: CustomAgentMCPServer[];
  /** Custom MCP server configurations specific to this agent */
  customMcpServers?: McpServerConfig[];
  /** Icon identifier for display (Lucide icon name) */
  icon?: string;
  /** Tags for categorization */
  tags?: string[];
  /** ISO timestamp of creation */
  createdAt: string;
  /** ISO timestamp of last update */
  updatedAt: string;
  /** User ID of creator (for multi-user support) */
  createdBy?: string;
}

/**
 * CustomAgentExecution - Record of a custom agent execution
 */
export interface CustomAgentExecution {
  /** Unique execution ID */
  id: string;
  /** ID of the custom agent that was executed */
  agentId: string;
  /** Execution status */
  status: 'running' | 'completed' | 'failed' | 'cancelled';
  /** Input provided to the agent */
  input: string;
  /** Output generated by the agent (if completed) */
  output?: string;
  /** Error message (if failed) */
  error?: string;
  /** Token usage statistics */
  tokenUsage?: {
    inputTokens: number;
    outputTokens: number;
    cacheReadInputTokens?: number;
    cacheCreationInputTokens?: number;
  };
  /** ISO timestamp of execution start */
  startedAt: string;
  /** ISO timestamp of execution completion */
  completedAt?: string;
}

/**
 * CreateCustomAgentInput - Input for creating a new custom agent
 */
export interface CreateCustomAgentInput {
  name: string;
  description: string;
  systemPrompt: string;
  modelConfig: CustomAgentModelConfig;
  tools?: CustomAgentTool[];
  mcpServers?: CustomAgentMCPServer[];
  customMcpServers?: McpServerConfig[];
  icon?: string;
  tags?: string[];
}

/**
 * UpdateCustomAgentInput - Input for updating an existing custom agent
 */
export interface UpdateCustomAgentInput {
  name?: string;
  description?: string;
  systemPrompt?: string;
  status?: CustomAgentStatus;
  modelConfig?: CustomAgentModelConfig;
  tools?: CustomAgentTool[];
  mcpServers?: CustomAgentMCPServer[];
  customMcpServers?: McpServerConfig[];
  icon?: string;
  tags?: string[];
}
